package com.core.beans;

// Generated Jun 30, 2013 12:00:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {

	private Integer id;
	private State state;
	private String name;
	private Set<User> users = new HashSet<User>(0);
	private Set<Patient> patients = new HashSet<Patient>(0);
	private Set<Clinic> clinics = new HashSet<Clinic>(0);

	public City() {
	}

	public City(State state, String name, Set<User> users,
			Set<Patient> patients, Set<Clinic> clinics) {
		this.state = state;
		this.name = name;
		this.users = users;
		this.patients = patients;
		this.clinics = clinics;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	public Set<Patient> getPatients() {
		return this.patients;
	}

	public void setPatients(Set<Patient> patients) {
		this.patients = patients;
	}

	public Set<Clinic> getClinics() {
		return this.clinics;
	}

	public void setClinics(Set<Clinic> clinics) {
		this.clinics = clinics;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append(id);
		builder.append(", ");
		builder.append(state);
		builder.append(", ");
		builder.append(name);
		builder.append(", ");
		builder.append(users);
		builder.append(", ");
		builder.append(patients);
		builder.append(", ");
		builder.append(clinics);
		return builder.toString();
	}
	

}
