package com.core.beans;

// Generated Jun 30, 2013 12:00:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Clinic generated by hbm2java
 */
public class Clinic implements java.io.Serializable {

	private Integer id;
	private City city;
	private String name;
	private String address;
	private String landPhone;
	private String mobilePhone;
	private String email;
	private String website;
	private String ministryNumber;
	private Set<Patient> patients = new HashSet<Patient>(0);

	public Clinic() {
	}

	public Clinic(City city, String name, String address, String landPhone,
			String mobilePhone, String email, String website,
			String ministryNumber, Set<Patient> patients) {
		this.city = city;
		this.name = name;
		this.address = address;
		this.landPhone = landPhone;
		this.mobilePhone = mobilePhone;
		this.email = email;
		this.website = website;
		this.ministryNumber = ministryNumber;
		this.patients = patients;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getLandPhone() {
		return this.landPhone;
	}

	public void setLandPhone(String landPhone) {
		this.landPhone = landPhone;
	}

	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getMinistryNumber() {
		return this.ministryNumber;
	}

	public void setMinistryNumber(String ministryNumber) {
		this.ministryNumber = ministryNumber;
	}

	public Set<Patient> getPatients() {
		return this.patients;
	}

	public void setPatients(Set<Patient> patients) {
		this.patients = patients;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append(id);
		builder.append(", ");
		builder.append(city);
		builder.append(", ");
		builder.append(name);
		builder.append(", ");
		builder.append(address);
		builder.append(", ");
		builder.append(landPhone);
		builder.append(", ");
		builder.append(mobilePhone);
		builder.append(", ");
		builder.append(email);
		builder.append(", ");
		builder.append(website);
		builder.append(", ");
		builder.append(ministryNumber);
		builder.append(", ");
		builder.append(patients);
		return builder.toString();
	}
	

}
