package com.core.beans;

// Generated Jun 30, 2013 12:00:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Job generated by hbm2java
 */
public class Job implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Set<User> users = new HashSet<User>(0);
	private Set<Patient> patients = new HashSet<Patient>(0);

	public Job() {
	}

	public Job(String name, String description, Set<User> users,
			Set<Patient> patients) {
		this.name = name;
		this.description = description;
		this.users = users;
		this.patients = patients;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	public Set<Patient> getPatients() {
		return this.patients;
	}

	public void setPatients(Set<Patient> patients) {
		this.patients = patients;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append(id);
		builder.append(", ");
		builder.append(name);
		builder.append(", ");
		builder.append(description);
		builder.append(", ");
		builder.append(users);
		builder.append(", ");
		builder.append(patients);
		return builder.toString();
	}
	

}
