package com.core.beans;

// Generated Jun 30, 2013 12:00:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * State generated by hbm2java
 */
public class State implements java.io.Serializable {

	private Integer id;
	private Country country;
	private String name;
	private Set<City> cities = new HashSet<City>(0);

	public State() {
	}

	public State(Country country, String name, Set<City> cities) {
		this.country = country;
		this.name = name;
		this.cities = cities;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<City> getCities() {
		return this.cities;
	}

	public void setCities(Set<City> cities) {
		this.cities = cities;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append(id);
		builder.append(", ");
		builder.append(country);
		builder.append(", ");
		builder.append(name);
		builder.append(", ");
		builder.append(cities);
		return builder.toString();
	}
	

}
