package com.core.beans;

// Generated Jun 30, 2013 12:00:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private City city;
	private Job job;
	private String nationalNumber;
	private String firstName;
	private String secondName;
	private String thirdName;
	private String lastName;
	private String address;
	private String landPhone;
	private String mobilePhone;
	private Date birthdate;
	private String website;
	private String email;
	private String username;
	private String password;
	private String role;

	public User() {
	}

	public User(String nationalNumber) {
		this.nationalNumber = nationalNumber;
	}

	public User(City city, Job job, String nationalNumber, String firstName,
			String secondName, String thirdName, String lastName,
			String address, String landPhone, String mobilePhone,
			Date birthdate, String website, String email, String username,
			String password, String role) {
		this.city = city;
		this.job = job;
		this.nationalNumber = nationalNumber;
		this.firstName = firstName;
		this.secondName = secondName;
		this.thirdName = thirdName;
		this.lastName = lastName;
		this.address = address;
		this.landPhone = landPhone;
		this.mobilePhone = mobilePhone;
		this.birthdate = birthdate;
		this.website = website;
		this.email = email;
		this.username = username;
		this.password = password;
		this.role = role;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	public String getNationalNumber() {
		return this.nationalNumber;
	}

	public void setNationalNumber(String nationalNumber) {
		this.nationalNumber = nationalNumber;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getSecondName() {
		return this.secondName;
	}

	public void setSecondName(String secondName) {
		this.secondName = secondName;
	}

	public String getThirdName() {
		return this.thirdName;
	}

	public void setThirdName(String thirdName) {
		this.thirdName = thirdName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getLandPhone() {
		return this.landPhone;
	}

	public void setLandPhone(String landPhone) {
		this.landPhone = landPhone;
	}

	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append(id);
		builder.append(", ");
		builder.append(city);
		builder.append(", ");
		builder.append(job);
		builder.append(", ");
		builder.append(nationalNumber);
		builder.append(", ");
		builder.append(firstName);
		builder.append(", ");
		builder.append(secondName);
		builder.append(", ");
		builder.append(thirdName);
		builder.append(", ");
		builder.append(lastName);
		builder.append(", ");
		builder.append(address);
		builder.append(", ");
		builder.append(landPhone);
		builder.append(", ");
		builder.append(mobilePhone);
		builder.append(", ");
		builder.append(birthdate);
		builder.append(", ");
		builder.append(website);
		builder.append(", ");
		builder.append(email);
		builder.append(", ");
		builder.append(username);
		builder.append(", ");
		builder.append(password);
		builder.append(", ");
		builder.append(role);
		return builder.toString();
	}
	

}
